import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, symlinkSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { canonicalJson, createEvidenceEnvelope, discoverJsonArtifacts, verifyEnvelopeIntegrity } from '@l9/assurance-evidence';
import { renderDecisionSummary, verifyDecision } from '@l9/assurance-evaluator';
import { InMemoryTestSigner } from '@l9/assurance-testing';
import { rootJson, passDecision } from '../helpers/fixtures.mjs';
test('payload tampering is detected',()=>{const observation=rootJson('fixtures','valid','tests.observation.json');const envelope=createEvidenceEnvelope(observation,'2026-07-21T00:00:02.000Z');assert.equal(verifyEnvelopeIntegrity(envelope),true);assert.equal(verifyEnvelopeIntegrity({...envelope,payload:{...observation,observationId:'changed'}}),false);});
test('malformed Unicode is rejected during canonicalization',()=>{assert.throws(()=>canonicalJson({value:'\ud800'}),/Unicode|surrogate/i);});
test('symlink escape is rejected by artifact discovery',()=>{const root=mkdtempSync(join(tmpdir(),'l9-assurance-'));const outside=mkdtempSync(join(tmpdir(),'l9-outside-'));try{writeFileSync(join(outside,'evidence.json'),'{}');symlinkSync(outside,join(root,'escape'));assert.throws(()=>discoverJsonArtifacts(root),/symbolic link/i);}finally{rmSync(root,{recursive:true,force:true});rmSync(outside,{recursive:true,force:true});}});
test('test signer is rejected by production verification',async()=>{const decision=await passDecision();const signer=new InMemoryTestSigner('fixture-key');const signature=signer.sign(canonicalJson(decision));const report=verifyDecision({...decision,signature});assert.equal(report.valid,false);assert.equal(report.signatureStatus,'invalid');});
test('Markdown projection escapes untrusted content',async()=>{const decision=await passDecision();const poisoned={...decision,unknowns:[{unknownId:'u',category:'other',description:'<script>alert(1)</script> [x](javascript:bad)',impact:'decision',relatedControls:[]}]};const summary=renderDecisionSummary(poisoned);assert.doesNotMatch(summary,/<script>/);assert.match(summary,/&lt;script&gt;/);});

test('artifact discovery rejects oversized files before parsing',()=>{const root=mkdtempSync(join(tmpdir(),'l9-large-'));try{writeFileSync(join(root,'large.json'),JSON.stringify({value:'x'.repeat(2048)}));assert.throws(()=>discoverJsonArtifacts(root,{maximumFileBytes:100}),/EVIDENCE_TOO_LARGE/);}finally{rmSync(root,{recursive:true,force:true});}});
test('direct non-JSON artifact paths are rejected',()=>{const root=mkdtempSync(join(tmpdir(),'l9-media-'));try{const file=join(root,'evidence.txt');writeFileSync(file,'{}');assert.throws(()=>discoverJsonArtifacts(file),/EVIDENCE_MEDIA_TYPE_UNSUPPORTED/);}finally{rmSync(root,{recursive:true,force:true});}});
test('decision verification rejects verdict reduction tampering',async()=>{const decision=await passDecision();const report=verifyDecision({...decision,verdict:'fail'});assert.equal(report.valid,false);assert.match(report.reasons.join(' '),/control reduction/);});
test('decision verification rejects nested unknown properties',async()=>{const decision=await passDecision();const controls=decision.controlResults.map((item,index)=>index===0?{...item,unexpected:true}:item);const report=verifyDecision({...decision,controlResults:controls});assert.equal(report.valid,false);assert.match(report.reasons.join(' '),/unknown property/);});
test('decision verification rejects dangling evidence references',async()=>{const decision=await passDecision();const controls=decision.controlResults.map((item,index)=>index===0?{...item,evidenceRefs:['missing-evidence']}:item);const report=verifyDecision({...decision,controlResults:controls});assert.equal(report.valid,false);assert.match(report.reasons.join(' '),/missing evidence/);});
