export const SCHEMA_VERSION = '1.0.0' as const;
export const OBSERVATION_SCHEMA = 'l9.observation' as const;
export const EVIDENCE_ENVELOPE_SCHEMA = 'l9.evidence-envelope' as const;
export const DECISION_SCHEMA = 'l9.assurance-decision' as const;
export const PLAN_SCHEMA = 'l9.assurance-plan' as const;
export const CANONICALIZATION_ALGORITHM = 'l9.canonical-json/v1' as const;

export const ADMISSION_REASON_CODES = [
  'EVIDENCE_MEDIA_TYPE_UNSUPPORTED',
  'EVIDENCE_TOO_LARGE',
  'EVIDENCE_SCHEMA_UNSUPPORTED',
  'EVIDENCE_SCHEMA_INVALID',
  'EVIDENCE_CANONICALIZATION_FAILED',
  'EVIDENCE_PAYLOAD_DIGEST_MISMATCH',
  'EVIDENCE_PRODUCER_UNKNOWN',
  'EVIDENCE_PRODUCER_VERSION_REVOKED',
  'EVIDENCE_CHECK_UNAUTHORIZED',
  'EVIDENCE_SUBJECT_INVALID',
  'EVIDENCE_SUBJECT_MISMATCH',
  'EVIDENCE_REVISION_MISMATCH',
  'EVIDENCE_EXECUTION_INTERVAL_INVALID',
  'EVIDENCE_STALE',
  'EVIDENCE_SIGNATURE_REQUIRED',
  'EVIDENCE_SIGNATURE_INVALID',
  'EVIDENCE_LINEAGE_INVALID',
  'EVIDENCE_REPLAY_DETECTED',
  'EVIDENCE_POLICY_INADMISSIBLE',
  'EVIDENCE_EXTENSION_NAMESPACE_INVALID',
  'EVIDENCE_LIMIT_EXCEEDED'
] as const;

export type AdmissionReasonCode = (typeof ADMISSION_REASON_CODES)[number];

export const CONTROL_REASON_CODES = [
  'CONTROL_REQUIREMENT_SATISFIED',
  'CONTROL_POSITIVE_FAILURE',
  'CONTROL_EVIDENCE_MISSING',
  'CONTROL_EVIDENCE_ERROR',
  'CONTROL_EVIDENCE_SKIPPED',
  'CONTROL_CARDINALITY_VIOLATION',
  'CONTROL_MANDATORY_FINDING_PRESENT',
  'CONTROL_SUBJECT_CONSISTENT',
  'CONTROL_NOT_APPLICABLE',
  'CONTROL_WAIVER_APPLIED',
  'CONTROL_WAIVER_EXPIRED',
  'CONTROL_WAIVER_UNAUTHORIZED',
  'CONTROL_POLICY_DISABLED',
  'CONTROL_POLICY_UNKNOWN_FAIL'
] as const;
export type ControlReasonCode = (typeof CONTROL_REASON_CODES)[number];

export const EXIT_CODES = Object.freeze({
  pass: 0,
  conditional: 10,
  fail: 20,
  indeterminate: 30,
  input: 40,
  policy: 41,
  admission: 42,
  signature: 43,
  invariant: 50
} as const);
