from __future__ import annotations

from types import MappingProxyType

ASSURANCE_ID = "l9-assurance"
ASSURANCE_VERSION = "2.1.1"
ASSURANCE_REPOSITORY = "Quantum-L9/l9-assurance"
SCHEMA_VERSION = "1.0.0"
CANONICALIZATION_ALGORITHM = "l9.canonical-json/v1"
OBSERVATION_SCHEMA = "l9.observation"
EVIDENCE_ENVELOPE_SCHEMA = "l9.evidence-envelope"
DECISION_SCHEMA = "l9.assurance-decision"
PLAN_SCHEMA = "l9.assurance-plan"
CAPABILITIES_SCHEMA = "l9.assurance-capabilities"

ADMISSION_REASON_CODES = (
    "EVIDENCE_MEDIA_TYPE_UNSUPPORTED",
    "EVIDENCE_TOO_LARGE",
    "EVIDENCE_SCHEMA_UNSUPPORTED",
    "EVIDENCE_SCHEMA_INVALID",
    "EVIDENCE_CANONICALIZATION_FAILED",
    "EVIDENCE_PAYLOAD_DIGEST_MISMATCH",
    "EVIDENCE_PRODUCER_UNKNOWN",
    "EVIDENCE_PRODUCER_VERSION_REVOKED",
    "EVIDENCE_CHECK_UNAUTHORIZED",
    "EVIDENCE_SUBJECT_INVALID",
    "EVIDENCE_SUBJECT_MISMATCH",
    "EVIDENCE_REVISION_MISMATCH",
    "EVIDENCE_EXECUTION_INTERVAL_INVALID",
    "EVIDENCE_STALE",
    "EVIDENCE_SIGNATURE_REQUIRED",
    "EVIDENCE_SIGNATURE_INVALID",
    "EVIDENCE_LINEAGE_INVALID",
    "EVIDENCE_REPLAY_DETECTED",
    "EVIDENCE_POLICY_INADMISSIBLE",
    "EVIDENCE_EXTENSION_NAMESPACE_INVALID",
    "EVIDENCE_LIMIT_EXCEEDED",
)

CONTROL_REASON_CODES = (
    "CONTROL_REQUIREMENT_SATISFIED",
    "CONTROL_POSITIVE_FAILURE",
    "CONTROL_EVIDENCE_MISSING",
    "CONTROL_EVIDENCE_ERROR",
    "CONTROL_EVIDENCE_SKIPPED",
    "CONTROL_CARDINALITY_VIOLATION",
    "CONTROL_MANDATORY_FINDING_PRESENT",
    "CONTROL_SUBJECT_CONSISTENT",
    "CONTROL_NOT_APPLICABLE",
    "CONTROL_WAIVER_APPLIED",
    "CONTROL_WAIVER_EXPIRED",
    "CONTROL_WAIVER_UNAUTHORIZED",
    "CONTROL_POLICY_DISABLED",
    "CONTROL_POLICY_UNKNOWN_FAIL",
)

EXIT_CODES = MappingProxyType(
    {
        "pass": 0,
        "conditional": 10,
        "fail": 20,
        "indeterminate": 30,
        "input": 40,
        "policy": 41,
        "admission": 42,
        "signature": 43,
        "invariant": 50,
    }
)
