import test from 'node:test';
import assert from 'node:assert/strict';
import { orderControls, ControlResolutionError } from '@l9/assurance-controls';
import { resolvePolicy, PolicyResolutionError, evaluateWaiver } from '@l9/assurance-policy';
import { controls, rootJson, subject, FIXED_TIME } from '../helpers/fixtures.mjs';
test('control ordering is deterministic and cycle detection is fail-closed',()=>{const ordered=orderControls(controls());assert.deepEqual(ordered.map((x)=>x.id),[...ordered.map((x)=>x.id)].sort());const [first,second]=controls();const cycle=[{...first,dependencies:[{id:second.id,version:second.version}]},{...second,dependencies:[{id:first.id,version:first.version}]}];assert.throws(()=>orderControls(cycle),ControlResolutionError);});
test('policy overlays apply by explicit precedence and conflicts fail',()=>{const base=rootJson('fixtures','compatibility','policy.json');const resolved=resolvePolicy(base,[{id:'org',precedence:10,policy:{mandatoryFindingSeverities:['critical']}}]);assert.deepEqual(resolved.policy.mandatoryFindingSeverities,['critical']);assert.throws(()=>resolvePolicy(base,[{id:'a',precedence:10,policy:{mandatoryFindingSeverities:['critical']}},{id:'b',precedence:10,policy:{mandatoryFindingSeverities:['high']}}]),PolicyResolutionError);});
test('active waiver is authorized and expired waiver is rejected',()=>{const policy=rootJson('fixtures','compatibility','policy.json');const waiver=rootJson('fixtures','valid','lint-waiver.json');const lint=controls().find((item)=>item.id==='L9.CI.LINT');assert.equal(evaluateWaiver(waiver,lint,subject(),policy,FIXED_TIME).valid,true);assert.equal(evaluateWaiver({...waiver,expiresAt:'2026-07-20T00:00:00.000Z'},lint,subject(),policy,FIXED_TIME).reason,'expired');});

test('runtime control parser rejects incomplete control objects',async()=>{const {parseControlDefinition}=await import('@l9/assurance-controls');assert.throws(()=>parseControlDefinition('{"id":"x"}'),/version/);});
test('runtime policy parser rejects unevaluable hard prohibitions',async()=>{const {parseAssurancePolicy}=await import('@l9/assurance-policy');const policy=rootJson('fixtures','compatibility','policy.json');assert.throws(()=>parseAssurancePolicy(JSON.stringify({...policy,hardProhibitions:[{id:'x',description:'x'}]})),/unsupported in Release zero/);});
test('policy rollback uses semantic prerelease ordering',()=>{const base={...rootJson('fixtures','compatibility','policy.json'),version:'1.0.0-alpha.2',minimumPolicyVersion:'1.0.0-alpha.10'};assert.throws(()=>resolvePolicy(base),PolicyResolutionError);});
test('control parser rejects inverted cardinality',async()=>{const {parseControlDefinition}=await import('@l9/assurance-controls');const control=structuredClone(controls().find((item)=>item.evidenceRequirements.length>0));control.evidenceRequirements[0].cardinality={minimum:2,maximum:1};assert.throws(()=>parseControlDefinition(JSON.stringify(control)),/maximum must be >= minimum/);});
