import test from 'node:test';
import assert from 'node:assert/strict';
import { canonicalJson, sha256Digest, normalizeSubject, admitObservations, InMemoryReplayStore, validateObservation } from '@l9/assurance-evidence';
import { trustedConfiguration, subject, validObservations, rootJson, FIXED_TIME } from '../helpers/fixtures.mjs';
test('canonical JSON is sorted, stable, and idempotent',()=>{const value={z:1,a:{d:4,c:3},b:[2,1]};const first=canonicalJson(value);assert.equal(first,'{"a":{"c":3,"d":4},"b":[2,1],"z":1}');assert.equal(canonicalJson(JSON.parse(first)),first);});
test('SHA-256 digest has explicit algorithm and stable value',()=>{const a=sha256Digest({b:2,a:1});const b=sha256Digest({a:1,b:2});assert.equal(a.algorithm,'sha256');assert.match(a.value,/^[a-f0-9]{64}$/);assert.deepEqual(a,b);});
test('subject normalization removes git suffix and normalizes host and commit',()=>{const normalized=normalizeSubject({...subject(),repository:{host:'GITHUB.COM',owner:'Quantum-L9',name:'example.git'},revision:{commit:'A'.repeat(40)}});assert.equal(normalized.repository.host,'github.com');assert.equal(normalized.repository.name,'example');assert.equal(normalized.revision.commit,'a'.repeat(40));});
test('valid observations are admitted and duplicate content is deduplicated',async()=>{const config=trustedConfiguration();const store=new InMemoryReplayStore();const first=await admitObservations(validObservations(),{subject:subject(),producerRegistry:config.producerRegistry,checkRegistry:config.checkRegistry,receivedAt:FIXED_TIME,channel:'local',replayStore:store});assert.equal(first.accepted.length,6);const duplicateA=rootJson('fixtures','adversarial','duplicate-a.observation.json');const duplicateB=rootJson('fixtures','adversarial','duplicate-b.observation.json');const report=await admitObservations([duplicateA,duplicateB],{subject:subject(),producerRegistry:config.producerRegistry,checkRegistry:config.checkRegistry,receivedAt:FIXED_TIME,channel:'local',replayStore:new InMemoryReplayStore()});assert.equal(report.accepted.length,1);assert.equal(report.duplicateCount,1);});
test('semantic validation rejects summary mismatch',()=>{const invalid=rootJson('fixtures','invalid','summary-mismatch.observation.json');const result=validateObservation(invalid);assert.equal(result.valid,false);assert.match(result.errors.join(' '),/findingCount/);});

test('nested unknown observation properties fail closed',()=>{const value=structuredClone(rootJson('fixtures','valid','tests.observation.json'));value.execution.unexpected=true;const result=validateObservation(value);assert.equal(result.valid,false);assert.match(result.errors.join(' '),/unknown property/);});
test('malformed artifact references fail structural validation',()=>{const value=structuredClone(rootJson('fixtures','valid','tests.observation.json'));value.artifacts=[{name:'bad',digest:{algorithm:'sha256',value:'nope'}}];const result=validateObservation(value);assert.equal(result.valid,false);assert.match(result.errors.join(' '),/artifacts\[0\]\.digest/);});
test('malformed provenance materials fail structural validation',()=>{const value=structuredClone(rootJson('fixtures','valid','tests.observation.json'));value.provenance={materials:[{name:'bad'}]};const result=validateObservation(value);assert.equal(result.valid,false);assert.match(result.errors.join(' '),/provenance\.materials/);});
test('producer subject-kind authorization is enforced',async()=>{const config=trustedConfiguration();const producer={...config.producerRegistry.producers[0],subject_kinds:['artifact']};const report=await admitObservations([rootJson('fixtures','valid','tests.observation.json')],{subject:subject(),producerRegistry:{...config.producerRegistry,producers:[producer]},checkRegistry:config.checkRegistry,receivedAt:FIXED_TIME,channel:'local'});assert.equal(report.rejectedCount,1);assert.match(report.results[0].reasons[0].message,/subject kind/);});
test('producer repository identity is enforced',async()=>{const config=trustedConfiguration();const value=structuredClone(rootJson('fixtures','valid','tests.observation.json'));value.producer.repository='Quantum-L9/not-sdk';const report=await admitObservations([value],{subject:subject(),producerRegistry:config.producerRegistry,checkRegistry:config.checkRegistry,receivedAt:FIXED_TIME,channel:'local'});assert.equal(report.rejectedCount,1);assert.match(report.results[0].reasons[0].message,/repository/);});
test('check output schema is enforced',async()=>{const config=trustedConfiguration();const check={...config.checkRegistry.checks.find((item)=>item.id==='l9.tests'),output_schema:'other/v1'};const checks=config.checkRegistry.checks.map((item)=>item.id===check.id?check:item);const report=await admitObservations([rootJson('fixtures','valid','tests.observation.json')],{subject:subject(),producerRegistry:config.producerRegistry,checkRegistry:{...config.checkRegistry,checks},receivedAt:FIXED_TIME,channel:'local'});assert.equal(report.rejectedCount,1);assert.equal(report.results[0].reasons[0].code,'EVIDENCE_SCHEMA_UNSUPPORTED');});
test('check execution-status authorization is enforced',async()=>{const config=trustedConfiguration();const original=config.checkRegistry.checks.find((item)=>item.id==='l9.tests');const check={...original,accepted_execution_statuses:['failed']};const checks=config.checkRegistry.checks.map((item)=>item.id===check.id?check:item);const report=await admitObservations([rootJson('fixtures','valid','tests.observation.json')],{subject:subject(),producerRegistry:config.producerRegistry,checkRegistry:{...config.checkRegistry,checks},receivedAt:FIXED_TIME,channel:'local'});assert.equal(report.rejectedCount,1);assert.equal(report.results[0].reasons[0].code,'EVIDENCE_CHECK_UNAUTHORIZED');});
test('semantic-version precedence handles numeric prerelease identifiers',async()=>{const {compareSemVer}=await import('@l9/assurance-evidence');assert.equal(compareSemVer('1.0.0-alpha.2','1.0.0-alpha.10')<0,true);assert.equal(compareSemVer('1.0.0-alpha','1.0.0')<0,true);});
